# Pandas Introduction

### Data Structures supported in Pandas:
-Series <br>
-DataFrames

#### Alka Pandey

In [1]:
import pandas as pd

In [2]:
# Create a dataframe from a Pandas series:pd.Series function

In [3]:
s1 = pd.Series([10,20,30,40]) #from list
s1

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
s2 = pd.Series((10,20,30,40)) #from tuple
s2

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
# creating empty series:

s2 = pd.Series()
s2

Series([], dtype: object)

In [6]:
# create a series from a numpy array:

import numpy as np
arr = np.array([10,40,60,20,77])
series = pd.Series(arr)
print(series)

0    10
1    40
2    60
3    20
4    77
dtype: int32

In [7]:
# creating a series from a dictionary:

data = {"a":99,"b":88,"c":44}
s4 = pd.Series(data)
print(s4)

a    99
b    88
c    44
dtype: int64

In [8]:
series

0    10
1    40
2    60
3    20
4    77
dtype: int32

In [9]:
# accessing elements in a series:

series[1:5]

1    40
2    60
3    20
4    77
dtype: int32

In [10]:
s4

a    99
b    88
c    44
dtype: int64

In [11]:
s4["b"]

88

In [12]:
s4[0]

99

In [13]:
s4["a"]

99

In [14]:
s4[-1]

44

In [15]:
s4[1:3]

b    88
c    44
dtype: int64

In [16]:
# filter operation

hello1 = pd.Series([1,2,3,4,6,7,8,9,10,15,20,50,90])
hello1filtered = hello1[hello1>8]

In [17]:
hello1filtered

7      9
8     10
9     15
10    20
11    50
12    90
dtype: int64

In [18]:
hello1 = pd.Series([100,200,3,4,60,7,8,9,10,15,20,50,90])
hello1filtered = hello1[hello1>8]
hello1filtered

0     100
1     200
4      60
7       9
8      10
9      15
10     20
11     50
12     90
dtype: int64

In [19]:
hello1[(hello1>8)==True]

0     100
1     200
4      60
7       9
8      10
9      15
10     20
11     50
12     90
dtype: int64

In [20]:
hello1 = pd.Series([100,200,3,4,60,7,8,9,10,15,20,50,90])
hello1filtered = hello1[(hello1>8) & (hello1<=50)]
hello1filtered

7      9
8     10
9     15
10    20
11    50
dtype: int64

In [21]:
hello1_reset = hello1filtered.reset_index(drop=True)
hello1_reset

0     9
1    10
2    15
3    20
4    50
dtype: int64

### Dataframes

In [22]:
#reading a file in dataframe pandas

data = pd.read_csv("datademo.csv")
data

   StudentID StudentName  Class  Age
0        101         ABC      5   10
1        102         HGF      7   13
2        103       SGADF      3    4
3        104        DGSF      4   13
4        105       SGHDF      9   14

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StudentID    5 non-null      int64
 1   StudentName  5 non-null      object
 2   Class        5 non-null      int64
 3   Age          5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

In [24]:
datap = pd.read_csv("C:\\Users\\alkap\\Downloads\\CN Asia Cup\\all_batsmen_data.csv")
datap

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09
...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [149]:
datap.sum()

Team           IndiaIndiaIndiaIndiaIndiaIndiaIndiaIndiaIndiaI...
Player         Rohit SharmaRohit SharmaRohit SharmaRohit Shar...
Filter         vs Pakistanvs Afghanistanvs Sri Lankavs Bangla...
Matches                                                      923
Runs                                                       16615
Highest                                                     7226
Average                                                  4415.05
Strike Rate                                             24002.66
NewCalc                                              3792.646706
dtype: object

In [25]:
datap.head(10)

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09
5,India,KL Rahul,vs Pakistan,1,3,3,3.00,37.50
6,India,KL Rahul,vs Afghanistan,1,69,69,69.00,143.75
7,India,KL Rahul,vs Sri Lanka,8,295,89,42.14,141.14
8,India,KL Rahul,vs Bangladesh,5,99,52,33.00,128.57
9,India,Virat Kohli,vs Pakistan,7,311,78,77.75,118.25

In [26]:
datap.tail()

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StudentID    5 non-null      int64
 1   StudentName  5 non-null      object
 2   Class        5 non-null      int64
 3   Age          5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

In [28]:
datap.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Team         200 non-null    object
 1   Player       200 non-null    object
 2   Filter       200 non-null    object
 3   Matches      200 non-null    int64
 4   Runs         200 non-null    int64
 5   Highest      200 non-null    int64
 6   Average      184 non-null    float64
 7   Strike Rate  200 non-null    float64
dtypes: float64(2), int64(3), object(3)
memory usage: 12.6+ KB

In [29]:
datap.isnull().sum()

Team            0
Player          0
Filter          0
Matches         0
Runs            0
Highest         0
Average        16
Strike Rate     0
dtype: int64

In [30]:
data.describe()

        StudentID     Class        Age
count    5.000000  5.000000   5.000000
mean   103.000000  5.600000  10.800000
std      1.581139  2.408319   4.086563
min    101.000000  3.000000   4.000000
25%    102.000000  4.000000  10.000000
50%    103.000000  5.000000  13.000000
75%    104.000000  7.000000  13.000000
max    105.000000  9.000000  14.000000

In [31]:
np.mean(data["Class"])

5.6

In [32]:
data["Class"].mean()

5.6

In [33]:
data[["StudentName"]] #accesing certain columns with column names: syntax is dataframe["colname"]

  StudentName
0         ABC
1         HGF
2       SGADF
3        DGSF
4       SGHDF

In [34]:
datap[["Player"]]

              Player
0       Rohit Sharma
1       Rohit Sharma
2       Rohit Sharma
3       Rohit Sharma
4       Rohit Sharma
..               ...
195       Aizaz Khan
196       Aizaz Khan
197  Scott McKechnie
198    Yasim Murtaza
199     Ayush Shukla

[200 rows x 1 columns]

In [35]:
datap["Player"].unique()

array(['Rohit Sharma', 'KL Rahul', 'Virat Kohli', 'Suryakumar Yadav',
       'Rishabh Pant', 'Deepak Hooda', 'Dinesh Karthik', 'Hardik Pandya',
       'Ravindra Jadeja', 'R Ashwin', 'Babar Azam', 'Shadab Khan',
       'Asif Ali', 'Fakhar Zaman', 'Haider Ali', 'Iftikhar Ahmed',
       'Khushdil Shah', 'Mohammad Nawaz', 'Mohammad Rizwan',
       'Mohammad Nabi', 'Najibullah Zadran', 'Afsar Zazai',
       'Azmatullah Omarzai', 'Hashmatullah Shahidi', 'Hazratullah Zazai',
       'Ibrahim Zadran', 'Karim Janat', 'Rahmanullah Gurbaz',
       'Rashid Khan', 'Samiullah Shinwari', 'Shakib Al Hasan',
       'Anamul Haque', 'Mushfiqur Rahim', 'Afif Hossain',
       'Mosaddek Hossain', 'Mahmudullah', 'Mahedi Hasan',
       'Mohammad Saifuddin', 'Sabbir Rahman', 'Mehidy Hasan Miraz',
       'Parvez Hossain Emon', 'Mohammad Naim', 'Dasun Shanaka',
       'Danushka Gunathilaka', 'Pathum Nissanka', 'Kusal Mendis',
       'Charith Asalanka', 'Bhanuka Rajapaksa', 'Ashen Bandara',
       'Dhananjaya de Silva', 'Wanindu Hasaranga', 'Dinesh Chandimal',
       'Nizakat Khan', 'Kinchit Shah', 'Zeeshan Ali', 'Haroon Arshad',
       'Babar Hayat', 'Aftab Hussain', 'Aizaz Khan', 'Scott McKechnie',
       'Yasim Murtaza', 'Ayush Shukla'], dtype=object)

In [36]:
datap["Player"].nunique()

62

In [37]:
datap["Player"].value_counts()

Player
Anamul Haque            6
Mahmudullah             6
Mushfiqur Rahim         6
Shakib Al Hasan         6
Samiullah Shinwari      6
                       ..
Afsar Zazai             1
Ashen Bandara           1
Hashmatullah Shahidi    1
Ibrahim Zadran          1
Ayush Shukla            1
Name: count, Length: 62, dtype: int64

In [38]:
data.columns

Index(['StudentID', 'StudentName', 'Class', 'Age'], dtype='object')

In [39]:
ffff = data[['StudentName', 'Class']]
ffff

  StudentName  Class
0         ABC      5
1         HGF      7
2       SGADF      3
3        DGSF      4
4       SGHDF      9

In [40]:
#create a dataframe

In [41]:
# create a dataframe from a list

lis2 = [80,80,90,70]
df = pd.DataFrame(lis2)
df

    0
0  80
1  80
2  90
3  70

In [42]:
# create a dataframe from a list of dictionary:

data2 = [{"a":10,"b":20,"x":777},{"a":20,"b":99,"c":100}]
df2 = pd.DataFrame(data2)
df2

    a   b      x      c
0  10  20  777.0    NaN
1  20  99    NaN  100.0

### Rename columns

In [43]:
# Option 1: rename column in pandas using the "rename" function:

df2.rename(columns={"x":"newcol","c":"newcol2"},inplace=True)
df2

    a   b  newcol  newcol2
0  10  20   777.0      NaN
1  20  99     NaN    100.0

In [44]:
# rename column in pandas without inplace = True:

neww = df2.rename(columns={"x":"newcol","c":"newcol2"})
neww

    a   b  newcol  newcol2
0  10  20   777.0      NaN
1  20  99     NaN    100.0

In [45]:
# rename option 2:

df2.columns = ["Col1","Col2","Col3","Col4"]

In [46]:
df2[df2["Col1"]>10] #filter based on a condition

   Col1  Col2  Col3   Col4
1    20    99   NaN  100.0

In [47]:
# example to create dataframe from a list of dictionaries and index change:

data3 = [{"a":10,"b":20},{"a":20,"b":99,"c":100}]
df3 = pd.DataFrame(data3,index=["first","second"])
df3

         a   b      c
first   10  20    NaN
second  20  99  100.0

In [48]:
df2

   Col1  Col2   Col3   Col4
0    10    20  777.0    NaN
1    20    99    NaN  100.0

In [49]:
datap

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09
...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00

In [50]:
datap["Runs"]>=100

0      False
1      False
2       True
3       True
4       True
       ...
195    False
196    False
197    False
198     True
199    False
Name: Runs, Length: 200, dtype: bool

In [51]:
newplayer100 = datap[datap["Runs"]>=100]
newplayer100

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09
7,India,KL Rahul,vs Sri Lanka,8,295,89,42.14,141.14
9,India,Virat Kohli,vs Pakistan,7,311,78,77.75,118.25
11,India,Virat Kohli,vs Sri Lanka,7,339,82,84.75,140.60
12,India,Virat Kohli,vs Bangladesh,4,129,57,64.50,113.15
16,India,Suryakumar Yadav,year 2022,12,428,117,38.90,189.38
21,India,Rishabh Pant,year 2022,13,260,52,26.00,135.51
23,India,Deepak Hooda,year 2022,9,274,104,54.80,161.17
31,India,Hardik Pandya,year 2022,13,281,51,31.22,139.80
35,India,Ravindra Jadeja,year 2022,7,166,46,55.33,146.90
67,Afghanistan,Mohammad Nabi,vs Bangladesh,8,141,84,28.20,128.18
68,Afghanistan,Mohammad Nabi,year 2022,10,130,43,18.57,123.80
73,Afghanistan,Najibullah Zadran,year 2022,10,255,57,31.87,144.06
80,Afghanistan,Hazratullah Zazai,vs Bangladesh,4,113,59,37.66,126.96
81,Afghanistan,Hazratullah Zazai,year 2022,8,205,59,29.28,134.86
90,Afghanistan,Rahmanullah Gurbaz,year 2022,9,145,53,16.11,116.93
97,Afghanistan,Samiullah Shinwari,vs Bangladesh,4,119,49,39.66,132.22
101,Bangladesh,Shakib Al Hasan,vs Pakistan,9,292,84,41.71,127.51
102,Bangladesh,Shakib Al Hasan,vs Sri Lanka,8,154,38,19.25,111.59
103,Bangladesh,Shakib Al Hasan,vs Afghanistan,8,137,70,22.83,112.29
105,Bangladesh,Shakib Al Hasan,year 2022,5,116,68,29.00,127.47
112,Bangladesh,Mushfiqur Rahim,vs India,11,229,72,32.71,119.89
114,Bangladesh,Mushfiqur Rahim,vs Sri Lanka,10,296,72,42.28,149.49
115,Bangladesh,Mushfiqur Rahim,vs Afghanistan,7,149,46,24.83,119.20
121,Bangladesh,Afif Hossain,year 2022,8,195,50,32.50,119.63
126,Bangladesh,Mahmudullah,vs India,11,185,33,23.12,125.85
127,Bangladesh,Mahmudullah,vs Pakistan,15,119,22,10.81,92.24
128,Bangladesh,Mahmudullah,vs Sri Lanka,11,271,43,38.71,148.08
129,Bangladesh,Mahmudullah,vs Afghanistan,8,169,45,24.14,121.58
138,Bangladesh,Sabbir Rahman,vs India,6,236,77,47.20,134.85
140,Bangladesh,Sabbir Rahman,vs Sri Lanka,7,155,80,22.14,115.67
146,Bangladesh,Mohammad Naim,vs India,3,143,81,47.66,133.64
151,Sri Lanka,Dasun Shanaka,vs India,18,273,74,22.75,123.52
152,Sri Lanka,Dasun Shanaka,vs Pakistan,8,118,54,16.85,120.40
154,Sri Lanka,Dasun Shanaka,year 2022,11,308,74,44.00,145.28
155,Sri Lanka,Danushka Gunathilaka,vs India,10,109,38,12.11,102.83
156,Sri Lanka,Danushka Gunathilaka,vs Pakistan,6,158,57,26.33,128.45
157,Sri Lanka,Danushka Gunathilaka,vs Bangladesh,4,102,42,25.50,130.76
158,Sri Lanka,Danushka Gunathilaka,year 2022,9,110,38,12.22,123.59
161,Sri Lanka,Pathum Nissanka,year 2022,11,326,75,29.63,114.38
162,Sri Lanka,Kusal Mendis,vs Bangladesh,4,191,70,47.75,169.02
164,Sri Lanka,Kusal Mendis,year 2022,6,143,69,28.60,102.87
166,Sri Lanka,Charith Asalanka,vs India,4,103,53,34.33,122.61
167,Sri Lanka,Charith Asalanka,year 2022,11,226,53,22.60,113.00
170,Sri Lanka,Bhanuka Rajapaksa,vs Pakistan,3,112,77,37.33,143.58
173,Sri Lanka,Dhananjaya de Silva,vs India,6,146,57,48.66,129.20
179,Sri Lanka,Dinesh Chandimal,vs India,9,140,35,15.55,91.50
180,Sri Lanka,Dinesh Chandimal,vs Pakistan,6,158,58,31.60,106.75
183,Sri Lanka,Dinesh Chandimal,year 2022,7,112,25,18.66,96.55
186,Hong Kong,Nizakat Khan,year 2022,8,249,81,31.12,114.74
188,Hong Kong,Kinchit Shah,year 2022,8,131,37,26.20,100.00
189,Hong Kong,Zeeshan Ali,year 2022,8,105,42,21.00,105.00
193,Hong Kong,Babar Hayat,year 2022,8,217,86,36.16,134.78
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86

In [52]:
newplayer100["Player"].unique()

array(['Rohit Sharma', 'KL Rahul', 'Virat Kohli', 'Suryakumar Yadav',
       'Rishabh Pant', 'Deepak Hooda', 'Hardik Pandya', 'Ravindra Jadeja',
       'Mohammad Nabi', 'Najibullah Zadran', 'Hazratullah Zazai',
       'Rahmanullah Gurbaz', 'Samiullah Shinwari', 'Shakib Al Hasan',
       'Mushfiqur Rahim', 'Afif Hossain', 'Mahmudullah', 'Sabbir Rahman',
       'Mohammad Naim', 'Dasun Shanaka', 'Danushka Gunathilaka',
       'Pathum Nissanka', 'Kusal Mendis', 'Charith Asalanka',
       'Bhanuka Rajapaksa', 'Dhananjaya de Silva', 'Dinesh Chandimal',
       'Nizakat Khan', 'Kinchit Shah', 'Zeeshan Ali', 'Babar Hayat',
       'Yasim Murtaza'], dtype=object)

### Fillna function to fill missing values(NaN) with the desired value

In [53]:
df2

   Col1  Col2   Col3   Col4
0    10    20  777.0    NaN
1    20    99    NaN  100.0

In [54]:
gg = df2.fillna("0") #not recommended
gg

   Col1  Col2   Col3   Col4
0    10    20  777.0      0
1    20    99      0  100.0

In [55]:
df2["Col4"].fillna("0") #recommended

0        0
1    100.0
Name: Col4, dtype: object

In [56]:
gg.info() #Info function helps you to understand no of rows, columns, how many not null values are there in a col, its corresponding data type, etc

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    2 non-null      int64
 1   Col2    2 non-null      int64
 2   Col3    2 non-null      object
 3   Col4    2 non-null      object
dtypes: int64(2), object(2)
memory usage: 196.0+ bytes

In [57]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    2 non-null      int64
 1   Col2    2 non-null      int64
 2   Col3    1 non-null      float64
 3   Col4    1 non-null      float64
dtypes: float64(2), int64(2)
memory usage: 196.0 bytes

In [58]:
gg2 = df2.fillna(0)
gg2

   Col1  Col2   Col3   Col4
0    10    20  777.0    0.0
1    20    99    0.0  100.0

### Creating a new column and assigning some value to it

In [59]:
gg2["newcol"] = 9999

In [60]:
gg2

   Col1  Col2   Col3   Col4  newcol
0    10    20  777.0    0.0    9999
1    20    99    0.0  100.0    9999

In [61]:
datap["NewCalc"] = datap["Runs"]/datap["Matches"]
datap

,Team,Player,Filter,Matches,Runs,Highest,Average,Strike Rate,NewCalc
0,India,Rohit Sharma,vs Pakistan,8,70,30,14.00,127.27,8.750000
1,India,Rohit Sharma,vs Afghanistan,2,75,74,75.00,156.25,37.500000
2,India,Rohit Sharma,vs Sri Lanka,18,339,118,21.18,138.93,18.833333
3,India,Rohit Sharma,vs Bangladesh,11,452,89,41.09,144.40,41.090909
4,India,Rohit Sharma,year 2022,13,290,64,24.16,140.09,22.307692
...,...,...,...,...,...,...,...,...,...
195,Hong Kong,Aizaz Khan,vs Afghanistan,5,15,12,15.00,100.00,3.000000
196,Hong Kong,Aizaz Khan,year 2022,8,50,20,8.33,86.20,6.250000
197,Hong Kong,Scott McKechnie,year 2022,8,29,11,7.25,90.62,3.625000
198,Hong Kong,Yasim Murtaza,year 2022,8,151,58,21.57,104.86,18.875000
199,Hong Kong,Ayush Shukla,year 2022,5,0,0,0.00,0.00,0.000000

In [62]:
gg2["final_value"] = gg2["Col1"]*gg2["Col2"]
gg2

   Col1  Col2   Col3   Col4  newcol  final_value
0    10    20  777.0    0.0    9999          200
1    20    99    0.0  100.0    9999         1980

### Subsetting in a dataframe based on a condition

In [63]:
gg3 = gg2[gg2["Col1"]<=10]
gg3

   Col1  Col2   Col3  Col4  newcol  final_value
0    10    20  777.0   0.0    9999          200

### Creating a new column and assigning some value to it

In [64]:
gg3.loc[:,"n"] = 0

C:\Users\alkap\AppData\Local\Temp\ipykernel_22904\3883699810.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gg3.loc[:,"n"] = 0

In [65]:
gg3

   Col1  Col2   Col3  Col4  newcol  final_value  n
0    10    20  777.0   0.0    9999          200  0

### Deleting in a dataframe using del function and pop function

In [66]:
del gg2["Col1"]

In [67]:
gg2

   Col2   Col3   Col4  newcol  final_value
0    20  777.0    0.0    9999          200
1    99    0.0  100.0    9999         1980

In [68]:
gg2.pop("Col2")

0    20
1    99
Name: Col2, dtype: int64

In [69]:
gg2

    Col3   Col4  newcol  final_value
0  777.0    0.0    9999          200
1    0.0  100.0    9999         1980

### loc and iloc functions to access rows in a dataframe

In [70]:
gg2

    Col3   Col4  newcol  final_value
0  777.0    0.0    9999          200
1    0.0  100.0    9999         1980

In [71]:
gg2.loc[1]

Col3              0.0
Col4            100.0
newcol         9999.0
final_value    1980.0
Name: 1, dtype: float64

In [72]:
gg2.iloc[1]

Col3              0.0
Col4            100.0
newcol         9999.0
final_value    1980.0
Name: 1, dtype: float64

In [73]:
df3

         a   b      c
first   10  20    NaN
second  20  99  100.0

In [74]:
df3.loc["first"]

a    10.0
b    20.0
c     NaN
Name: first, dtype: float64

In [75]:
df3.loc[0] #throws an error because index is not an integer, explicitly mentioned string index

KeyError: 0

In [77]:
df3.iloc[0]

a    10.0
b    20.0
c     NaN
Name: first, dtype: float64

In [78]:
df = pd.DataFrame({'Name': ['John', 'Anna',"abc"],'Age': [28, 22,60],'City': ['New York', 'Los Angeles',"xyz"]})

df

   Name  Age         City
0  John   28     New York
1  Anna   22  Los Angeles
2   abc   60          xyz

In [79]:
df.drop("Age",axis=1,inplace=True)
df

   Name         City
0  John     New York
1  Anna  Los Angeles
2   abc          xyz

In [80]:
new_row = {"Name":"Newname","Age":1000,"City":"Chicago"}
new_row

{'Name': 'Newname', 'Age': 1000, 'City': 'Chicago'}

In [81]:
dfnew = df._append(new_row,ignore_index=True)
dfnew

      Name         City     Age
0     John     New York     NaN
1     Anna  Los Angeles     NaN
2      abc          xyz     NaN
3  Newname      Chicago  1000.0

In [82]:
new_rows = pd.DataFrame({'Name': ['X', 'Y'],'Age': [281, 221],'City': ['NY', 'LA']})
new_rows

  Name  Age City
0    X  281   NY
1    Y  221   LA

In [83]:
df

   Name         City
0  John     New York
1  Anna  Los Angeles
2   abc          xyz

In [84]:
# append multiple rows using concat: syntax is pd.concat([df1,df2])

dfnew2 = pd.concat([df,new_rows])
dfnew2

   Name         City    Age
0  John     New York    NaN
1  Anna  Los Angeles    NaN
2   abc          xyz    NaN
0     X           NY  281.0
1     Y           LA  221.0

In [85]:
data = {"one":pd.Series([1,2,3],index=["a","b","c"]),
       "two":pd.Series([1,2,3,4],index=["a","b","c","d"])}

data

{'one': a    1
 b    2
 c    3
 dtype: int64,
 'two': a    1
 b    2
 c    3
 d    4
 dtype: int64}

In [86]:
dd = pd.DataFrame(data)
dd

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [87]:
dd.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   one     3 non-null      float64
 1   two     4 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 96.0+ bytes

In [88]:
dd.isnull()

     one    two
a  False  False
b  False  False
c  False  False
d   True  False

In [89]:
dd.isnull().sum()

one    1
two    0
dtype: int64

In [90]:
dd.drop("one",axis=1,inplace=True) #first way

# dd = dd.drop("one",axis=1)  --> second way

In [91]:
dd

   two
a    1
b    2
c    3
d    4

In [92]:
dd.to_csv("myfile.csv")

# Concat

In [93]:
df1 = pd.DataFrame({"ID":[1,2,3],"Name":["Alice","Bob","Charlie"],"Age":[25,30,35]})
df1

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35

In [94]:
df2 = pd.DataFrame({"ID":[4,5,6,7],"Name":["David","Eve","Frank","Gilbert"],"Age":[40,45,50,70]})
df2

   ID     Name  Age
0   4    David   40
1   5      Eve   45
2   6    Frank   50
3   7  Gilbert   70

In [95]:
# Stack dataframes vertically using concat:

stackedvertical = pd.concat([df1,df2],axis=0,ignore_index=True)
stackedvertical

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
4   5      Eve   45
5   6    Frank   50
6   7  Gilbert   70

In [96]:
df3 = pd.DataFrame({"ID":[1,2,3,4],"Name":["Alice","Bob","Charlie","Helen"]})
df3

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    Helen

In [97]:
df4 = pd.DataFrame({"Age":[10,20,30],"Salary":[1000,2000,3000]})
df4

   Age  Salary
0   10    1000
1   20    2000
2   30    3000

In [98]:
stackedhorizontal = pd.concat([df3,df4],axis=1)
stackedhorizontal

   ID     Name   Age  Salary
0   1    Alice  10.0  1000.0
1   2      Bob  20.0  2000.0
2   3  Charlie  30.0  3000.0
3   4    Helen   NaN     NaN

# Merge

In [189]:
df5 = pd.DataFrame({"ID":[1,2,3,4],"Name":["Alice","Bob","Charlie","David"],"Age":[25,30,35,40]})
df5

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40

In [192]:
df6 = pd.DataFrame({"ID":[3,4,5,6],"Name":["Charlie","David","Eve","Frank"],"Age":[35,40,50,70]})
df6

   ID     Name  Age
0   3  Charlie   35
1   4    David   40
2   5      Eve   50
3   6    Frank   70

In [193]:
innerj = pd.merge(df5,df6,on="ID",how="inner")
innerj

   ID   Name_x  Age_x   Name_y  Age_y
0   3  Charlie     35  Charlie     35
1   4    David     40    David     40

In [102]:
innerj_clean = innerj.drop(["Name_y","Age_y"],axis=1)
innerj_clean

   ID   Name_x  Age_x
0   3  Charlie     35
1   4    David     40

In [103]:
innerj_clean.columns = ["ID","Name","Age"]
innerj_clean

   ID     Name  Age
0   3  Charlie   35
1   4    David   40

In [104]:
leftj = pd.merge(df5,df6,on="ID",how="left")
leftj

   ID   Name_x  Age_x   Name_y  Age_y
0   1    Alice     25      NaN    NaN
1   2      Bob     30      NaN    NaN
2   3  Charlie     35  Charlie   35.0
3   4    David     40    David   40.0

In [105]:
rightj = pd.merge(df5,df6,on="ID",how="right")
rightj

   ID   Name_x  Age_x   Name_y  Age_y
0   3  Charlie   35.0  Charlie     35
1   4    David   40.0    David     40
2   5      NaN    NaN      Eve     50
3   6      NaN    NaN    Frank     70

In [106]:
outerj = pd.merge(df5,df6,on="ID",how="outer")
outerj

   ID   Name_x  Age_x   Name_y  Age_y
0   1    Alice   25.0      NaN    NaN
1   2      Bob   30.0      NaN    NaN
2   3  Charlie   35.0  Charlie   35.0
3   4    David   40.0    David   40.0
4   5      NaN    NaN      Eve   50.0
5   6      NaN    NaN    Frank   70.0

# Join - works on index

In [107]:
data_cust = pd.DataFrame({"Name":["Alice","Bob","Charlie"],"City":["A","B","c"]})
data_cust

      Name City
0    Alice    A
1      Bob    B
2  Charlie    c

In [108]:
data_cust.index.name = "customer_id"
data_cust

                Name City
customer_id
0              Alice    A
1                Bob    B
2            Charlie    c

In [109]:
data_order = pd.DataFrame({"order_amount":[22,44,55],"order_date":["X","Y","Z"]})
data_order

   order_amount order_date
0            22          X
1            44          Y
2            55          Z

In [110]:
data_order.index.name = "customer_id"

In [111]:
data_order

             order_amount order_date
customer_id
0                      22          X
1                      44          Y
2                      55          Z

In [112]:
joined_df = data_cust.join(data_order)
joined_df

                Name City  order_amount order_date
customer_id
0              Alice    A            22          X
1                Bob    B            44          Y
2            Charlie    c            55          Z

## Handling missing values

In [113]:
df5 = pd.DataFrame({"ID":[1,2,3,4,7,8],"Name":["Alice","Bob","Charlie","Dex","Evie","Google"],"Age":[25,30,35,40,80,70]})
df6 = pd.DataFrame({"ID":[3,4,5,6,9,10],"Name":["Charlie","David","Eve","Frank","X","Y"],"Age":[35,40,50,70,80,70]})
dfm = pd.merge(df5,df6,on="ID",how="outer")
dfm

   ID   Name_x  Age_x   Name_y  Age_y
0   1    Alice   25.0      NaN    NaN
1   2      Bob   30.0      NaN    NaN
2   3  Charlie   35.0  Charlie   35.0
3   4      Dex   40.0    David   40.0
4   7     Evie   80.0      NaN    NaN
5   8   Google   70.0      NaN    NaN
6   5      NaN    NaN      Eve   50.0
7   6      NaN    NaN    Frank   70.0
8   9      NaN    NaN        X   80.0
9  10      NaN    NaN        Y   70.0

In [114]:
dfm.isnull().sum()

ID        0
Name_x    4
Age_x     4
Name_y    4
Age_y     4
dtype: int64

In [115]:
dfm.dropna() #all the rows with any missing value will be removed

   ID   Name_x  Age_x   Name_y  Age_y
2   3  Charlie   35.0  Charlie   35.0
3   4      Dex   40.0    David   40.0

In [208]:
dfm["Age_x"] = dfm["Age_x"].fillna(dfm["Age_x"].mean()) #Imputing missing values with the mean

In [209]:
dfm

   ID   Name_x      Age_x   Name_y  Age_y
0   1    Alice  25.000000      NaN    NaN
1   2      Bob  30.000000      NaN    NaN
2   3  Charlie  35.000000  Charlie   35.0
3   4      Dex  40.000000    David   40.0
4   7     Evie  80.000000      NaN    NaN
5   8   Google  70.000000      NaN    NaN
6   5  Unknown  46.666667      Eve   50.0
7   6  Unknown  46.666667    Frank   70.0
8   9  Unknown  46.666667        X   80.0
9  10  Unknown  46.666667        Y   70.0

In [118]:
dfm["Name_x"] = dfm["Name_x"].fillna("Unknown") #Impute misssing values of a categorical column like name with a string
dfm

   ID   Name_x      Age_x   Name_y  Age_y
0   1    Alice  25.000000      NaN    NaN
1   2      Bob  30.000000      NaN    NaN
2   3  Charlie  35.000000  Charlie   35.0
3   4      Dex  40.000000    David   40.0
4   7     Evie  80.000000      NaN    NaN
5   8   Google  70.000000      NaN    NaN
6   5  Unknown  46.666667      Eve   50.0
7   6  Unknown  46.666667    Frank   70.0
8   9  Unknown  46.666667        X   80.0
9  10  Unknown  46.666667        Y   70.0

In [119]:
# Sample DataFrame
df = pd.DataFrame({
    'ID': [4, 5, 6, 7],
    'Name': ['Alice', 'Bob', None, 'David']
})
df

   ID   Name
0   4  Alice
1   5    Bob
2   6   None
3   7  David

In [120]:
df.loc[df['ID'] == 6,"Name"] = "Charles"

In [121]:
# Fill 'Name' with a specific value where ID is 6
df.loc[df['ID'] == 6, 'Name'] = 'Charlie'

print(df)

   ID     Name
0   4    Alice
1   5      Bob
2   6  Charlie
3   7    David

In [122]:
import numpy as np

In [123]:
type(np.NaN)

float

# Pivot_Table

In [124]:
df = pd.DataFrame({
    'A': ['John', 'Boby', 'Mina', 'Peter', 'Nicky',"Nicky","Mina","John"],
    'B': ['Masters', 'Graduate', 'Graduate', 'Masters', 'Graduate',"Graduate","Graduate","Masters"],
    'C': [27, 23, 21, 23, 24,70,50,20]
})

df

#data - the dataframe to pivot
#values - The columns to aggregate
#index - Rows of pivot table
# columns - Th columns for pivot_table
# aggfunc - what function to apply whether sum,mean,count,etc

       A         B   C
0   John   Masters  27
1   Boby  Graduate  23
2   Mina  Graduate  21
3  Peter   Masters  23
4  Nicky  Graduate  24
5  Nicky  Graduate  70
6   Mina  Graduate  50
7   John   Masters  20

In [125]:
table = pd.pivot_table(df, index=['A', 'B'],values="C",aggfunc="sum")
table

                 C
A     B
Boby  Graduate  23
John  Masters   47
Mina  Graduate  71
Nicky Graduate  94
Peter Masters   23

In [126]:
table = pd.pivot_table(df, index=['A'],values="C",aggfunc="count")
table

       C
A
Boby   1
John   2
Mina   2
Nicky  2
Peter  1

In [127]:
df

       A         B   C
0   John   Masters  27
1   Boby  Graduate  23
2   Mina  Graduate  21
3  Peter   Masters  23
4  Nicky  Graduate  24
5  Nicky  Graduate  70
6   Mina  Graduate  50
7   John   Masters  20

In [128]:
table = pd.pivot_table(df, index=['A'],columns= "B",values="C",aggfunc="sum")
table

B      Graduate  Masters
A
Boby       23.0      NaN
John        NaN     47.0
Mina       71.0      NaN
Nicky      94.0      NaN
Peter       NaN     23.0

In [129]:
table = pd.pivot_table(df, index=['B'],columns= "A",values="C",aggfunc="mean")
table

A         Boby  John  Mina  Nicky  Peter
B
Graduate  23.0   NaN  35.5   47.0    NaN
Masters    NaN  23.5   NaN    NaN   23.0

In [130]:
df[["C"]].mean()

C    32.25
dtype: float64

In [131]:
dfm[["Age_x","Age_y"]].mean()

Age_x    46.666667
Age_y    57.500000
dtype: float64

In [132]:
dfm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      10 non-null     int64
 1   Name_x  10 non-null     object
 2   Age_x   10 non-null     float64
 3   Name_y  6 non-null      object
 4   Age_y   6 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 532.0+ bytes

In [133]:
dfm.describe()

             ID      Age_x      Age_y
count  10.00000  10.000000   6.000000
mean    5.50000  46.666667  57.500000
std     3.02765  16.942167  18.371173
min     1.00000  25.000000  35.000000
25%     3.25000  36.250000  42.500000
50%     5.50000  46.666667  60.000000
75%     7.75000  46.666667  70.000000
max    10.00000  80.000000  80.000000

In [134]:
dfm.columns

Index(['ID', 'Name_x', 'Age_x', 'Name_y', 'Age_y'], dtype='object')

In [135]:
#Missing value

In [136]:
import pandas as pd
import numpy as np
df = pd.DataFrame({"Name":["Ap","Dp","Sp","Qp",None],"Age":[26,np.nan,30,35,45]})
df

   Name   Age
0    Ap  26.0
1    Dp   NaN
2    Sp  30.0
3    Qp  35.0
4  None  45.0

In [137]:
df.isnull().sum() #check how many missing values are there in the dataset

Name    1
Age     1
dtype: int64

In [138]:
#drop missing values:

cleandf = df.dropna()
cleandf

  Name   Age
0   Ap  26.0
2   Sp  30.0
3   Qp  35.0

In [139]:
df

   Name   Age
0    Ap  26.0
1    Dp   NaN
2    Sp  30.0
3    Qp  35.0
4  None  45.0

In [140]:
# fill the missing values:

cleandf2 = df.fillna({"Name":"Unknown_Name","Age":df["Age"].mean()})
cleandf2

           Name   Age
0            Ap  26.0
1            Dp  34.0
2            Sp  30.0
3            Qp  35.0
4  Unknown_Name  45.0

In [141]:
#Pivot table

In [142]:
#data : df
# values : the column names for aggregation
# index : column name in row
# columns : column name in column
# aggfunc : what function to apply on the value column

In [143]:
data = {"Region":["East","West","East","North","East","South"],
       "Product":["A","B","A","B","C","A"],
       "Sales":[100,200,150,400,500,100]}

df = pd.DataFrame(data)
df

  Region Product  Sales
0   East       A    100
1   West       B    200
2   East       A    150
3  North       B    400
4   East       C    500
5  South       A    100

In [144]:
sales_summary = pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc="sum")
sales_summary

Product      A      B      C
Region
East     250.0    NaN  500.0
North      NaN  400.0    NaN
South    100.0    NaN    NaN
West       NaN  200.0    NaN

In [145]:
sales_summary.fillna(0)

Product      A      B      C
Region
East     250.0    0.0  500.0
North      0.0  400.0    0.0
South    100.0    0.0    0.0
West       0.0  200.0    0.0

In [146]:
data2 = {"Region":["East","West","East","North","East","South"],
       "Product":["A","B","A","B","C","A"],
       "Sales":[100,200,150,400,500,100],
        "Profit":[10,20,15,40,50,10]}

df2 = pd.DataFrame(data2)
df2

  Region Product  Sales  Profit
0   East       A    100      10
1   West       B    200      20
2   East       A    150      15
3  North       B    400      40
4   East       C    500      50
5  South       A    100      10

In [147]:
# multiple aggregations:

summary = pd.pivot_table(df2,values=["Sales","Profit"],index="Region",aggfunc={"Sales":["sum","mean"],"Profit":"max"})
summary

       Profit  Sales
          max   mean  sum
Region
East       50  250.0  750
North      40  400.0  400
South      10  100.0  100
West       20  200.0  200

In [148]:
#multi-level indexing

summary = pd.pivot_table(df2,values=["Sales","Profit"],index=["Region","Product"],aggfunc="sum",margins=True,margins_name="Total")
summary

                Profit  Sales
Region Product
East   A            25    250
       C            50    500
North  B            40    400
South  A            10    100
West   B            20    200
Total              145   1450

In [150]:
df

  Region Product  Sales
0   East       A    100
1   West       B    200
2   East       A    150
3  North       B    400
4   East       C    500
5  South       A    100

# Iterating over a dataframe

In [154]:
d = pd.DataFrame(np.random.rand(5,4),columns=["C1","C2","C3","C4"])
d

         C1        C2        C3        C4
0  0.832328  0.568732  0.831564  0.465060
1  0.552774  0.851489  0.885173  0.641729
2  0.049154  0.416317  0.826673  0.279977
3  0.759421  0.334034  0.174990  0.476024
4  0.141996  0.233591  0.958241  0.807277

In [159]:
# Method 1: Via .items()
for k,v in d.items():
    print("Key:",k)
    print("Value is:")
    print(v)

Key: C1
Value is:
0    0.832328
1    0.552774
2    0.049154
3    0.759421
4    0.141996
Name: C1, dtype: float64
Key: C2
Value is:
0    0.568732
1    0.851489
2    0.416317
3    0.334034
4    0.233591
Name: C2, dtype: float64
Key: C3
Value is:
0    0.831564
1    0.885173
2    0.826673
3    0.174990
4    0.958241
Name: C3, dtype: float64
Key: C4
Value is:
0    0.465060
1    0.641729
2    0.279977
3    0.476024
4    0.807277
Name: C4, dtype: float64

In [160]:
# Method 2: Via .iterrows()
for k,v in d.iterrows():
    print("Key:",k)
    print("Value is:")
    print(v)

Key: 0
Value is:
C1    0.832328
C2    0.568732
C3    0.831564
C4    0.465060
Name: 0, dtype: float64
Key: 1
Value is:
C1    0.552774
C2    0.851489
C3    0.885173
C4    0.641729
Name: 1, dtype: float64
Key: 2
Value is:
C1    0.049154
C2    0.416317
C3    0.826673
C4    0.279977
Name: 2, dtype: float64
Key: 3
Value is:
C1    0.759421
C2    0.334034
C3    0.174990
C4    0.476024
Name: 3, dtype: float64
Key: 4
Value is:
C1    0.141996
C2    0.233591
C3    0.958241
C4    0.807277
Name: 4, dtype: float64

In [161]:
# Method 3: Via .itertuples()
for t in d.itertuples():
    print(t)

Pandas(Index=0, C1=0.832327620930234, C2=0.5687319808327386, C3=0.8315641362785664, C4=0.4650604357005922)
Pandas(Index=1, C1=0.5527737029332498, C2=0.8514893717412859, C3=0.8851734878740837, C4=0.6417292269472402)
Pandas(Index=2, C1=0.04915449122631366, C2=0.4163173396570372, C3=0.8266729290356448, C4=0.2799774668285354)
Pandas(Index=3, C1=0.7594205476616895, C2=0.334033639901698, C3=0.17499044864568303, C4=0.47602429971646587)
Pandas(Index=4, C1=0.14199601708374365, C2=0.23359093227937067, C3=0.9582413172452591, C4=0.8072765982880767)

# Groupby

In [178]:
data = {"Category":["Grocery","Utility","Grocery","Loans","Utility","Grocery"],"Value":[100,120,150,130,300,300]}
data

{'Category': ['Grocery', 'Utility', 'Grocery', 'Loans', 'Utility', 'Grocery'],
 'Value': [100, 120, 150, 130, 300, 300]}

In [179]:
d2 = pd.DataFrame(data)
d2

  Category  Value
0  Grocery    100
1  Utility    120
2  Grocery    150
3    Loans    130
4  Utility    300
5  Grocery    300

In [180]:
d2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  6 non-null      object
 1   Value     6 non-null      int64
dtypes: int64(1), object(1)
memory usage: 228.0+ bytes

In [182]:
d2.groupby("Category")["Value"].sum()

Category
Grocery    550
Loans      130
Utility    420
Name: Value, dtype: int64

In [183]:
d2.groupby("Category")["Value"].count()

Category
Grocery    3
Loans      1
Utility    2
Name: Value, dtype: int64

In [185]:
d2.groupby("Category").groups

{'Grocery': [0, 2, 5], 'Loans': [3], 'Utility': [1, 4]}

In [194]:
d2.groupby("Category").get_group("Grocery")

  Category  Value
0  Grocery    100
2  Grocery    150
5  Grocery    300

In [198]:
df2

  Region Product  Sales  Profit
0   East       A    100      10
1   West       B    200      20
2   East       A    150      15
3  North       B    400      40
4   East       C    500      50
5  South       A    100      10

In [204]:
#Another example of group by with agg function

df2.groupby(["Region"]).agg(Total_Sales = ("Sales",sum),Average_Profit=("Profit",np.mean))

        Total_Sales  Average_Profit
Region
East            750            25.0
North           400            40.0
South           100            10.0
West            200            20.0

In [205]:
new_grouped_df = df2.groupby(["Region","Product"]).agg(Total_Sales = ("Sales",sum),Average_Profit=("Profit",np.mean))
new_grouped_df

                Total_Sales  Average_Profit
Region Product
East   A                250            12.5
       C                500            50.0
North  B                400            40.0
South  A                100            10.0
West   B                200            20.0

In [207]:
new_grouped_df2 = df2.groupby(["Region"]).agg({"Sales":sum,"Profit":np.median})
new_grouped_df2

        Sales  Profit
Region
East      750    15.0
North     400    40.0
South     100    10.0
West      200    20.0